version: "3.7"

services:
  db:
    restart: always
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: "todo"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      - 3306:3306
    expose:
      - 3306
    volumes:
      - mydb:/var/lib/mysql

volumes:
  mydb:
